baseURL = "http://localhost:1313/"
publishDir = "tmp/public"
resourceDir = "tmp/resources"
enableRobotsTXT = true

URL = "localhost:1313" # Updated for clarity
title = "Dev Open Neuromorphic" # Updated title
