baseURL = "https://open-neuromorphic.org/" # Updated baseURL
enableRobotsTXT = true

URL = "open-neuromorphic.org" # Updated URL

# [services]
# [services.googleAnalytics]
# ID = "G-YOUR_ONM_GA_ID" # Replace with ONM's Google Analytics ID
